### ISSUE TITLE
mac 下安装问题

### ISSUE THREAD

**Issue by juntingl** [Prodesire/Python-Guide-CN#39]

**Comment by juntingl** [comment]
mac 下 执行 此命令: pip install -r requirements.txt  （sudo 过的）还是会在安装依赖的时候报错！
Exception:
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip/req/req_set.py", line 784, in install

**Comment by Prodesire** [comment]
麻烦将报错贴全一点哈~

**Comment by Prodesire** [comment]
mac 下用系统默认的pip来装通常会有权限问题，有如下解法：
`pip install -r requirement.txt --user`
